services:
  mysql:
    image: mysql:8
    container_name: badminton-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: badminton
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: badminton-backend:latest
    container_name: badminton-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    volumes:
      - ./storage:/app/storage

volumes:
  mysql-data:
